- alias: Trimite temperatura pe telegram
  trigger:
  - platform: numeric_state
    entity_id: sensor.temperature_and_humidity_sensor_temperatura
    above: 30
  action:
  - service: rest_command.send_to_n8n
  mode: single
  id: 192d66874f544f65a031dfd2f1ef4882
- alias: Control motor_inainte 10s ON / 5s OFF pe temperatura si timp
  trigger:
  - platform: time_pattern
    seconds: /15
  condition:
  - condition: time
    after: '10:00:00'
    before: '16:00:00'
  - condition: template
    value_template: '{{ state_attr(''weather.forecast_home'', ''temperature'') | float
      > 25 }}'
  action:
  - service: script.porneste_motor_10sec
  id: 55c3561e1571476ab5e275fe5f86bd2c
- alias: Porneste motorul la ora 10:00
  id: motor_start_10
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
  - condition: template
    value_template: '{{ state_attr(''weather.forecast_home'', ''temperature'') | float
      > 20 }}

      '
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.motor_inainte
  - service: timer.start
    target:
      entity_id: timer.motor_timer
- alias: Opreste motorul dupa timer
  id: motor_stop_dupa_timer
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.motor_timer
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.motor_inainte
- id: '1750791933751'
  alias: Bec
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Aprinde lumina din dormitor
  conditions: []
  actions:
  - type: turn_on
    device_id: 4ce43f89962024ede5b58424cd89a024
    entity_id: 91fbd3f3a501c5cd0fb9309418eebeae
    domain: light
    brightness_pct: 90
  mode: single
- id: '1750792002560'
  alias: Stinge Bec
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Stinge lumina din dormitor
  conditions: []
  actions:
  - type: turn_off
    device_id: 4ce43f89962024ede5b58424cd89a024
    entity_id: 91fbd3f3a501c5cd0fb9309418eebeae
    domain: light
  mode: single
- id: '1750792665977'
  alias: Lumina Locatie
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: '21:00:00'
  conditions:
  - condition: device
    device_id: a9f818ff0f1ee02cd9c1ead141bc6ebf
    domain: device_tracker
    entity_id: e6d5bb29d4fbf0f0b05a8eeec60856fd
    type: is_home
  actions:
  - type: turn_on
    device_id: 4ce43f89962024ede5b58424cd89a024
    entity_id: 91fbd3f3a501c5cd0fb9309418eebeae
    domain: light
    brightness_pct: 100
  mode: single
- id: '1750854956532'
  alias: Stinge aerul conditionat
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Oprește aerul condiționat
  conditions: []
  actions:
  - action: google_assistant_sdk.send_text_command
    metadata: {}
    data:
      command: 'action: google_assistant_sdk.send_text_command data:   command: "turn
        off kitchen AC"'
  mode: single
- id: '1750862244518'
  alias: Seteaza temperatura
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Setează temperatura la {number}
  conditions: []
  actions:
  - action: google_assistant_sdk.send_text_command
    metadata: {}
    data:
      command: 'action: google_assistant_sdk.send_text_command data:   command: "Set
        the AC to {{ trigger.slots.number }} degrees"'
  mode: single
- id: '1750872487926'
  alias: Porneste PC
  description: ''
  triggers:
  - trigger: conversation
    command: Pornește calculatorul
  conditions: []
  actions:
  - action: wake_on_lan.send_magic_packet
    metadata: {}
    data:
      broadcast_port: 9
      mac: yourmacaddress
  mode: single
- id: '1750872877533'
  alias: Notificare Bec
  description: ''
  triggers:
  - device_id: a9f818ff0f1ee02cd9c1ead141bc6ebf
    domain: device_tracker
    entity_id: e6d5bb29d4fbf0f0b05a8eeec60856fd
    type: leaves
    trigger: device
    zone: zone.home
  conditions:
  - condition: device
    type: is_on
    device_id: 4ce43f89962024ede5b58424cd89a024
    entity_id: 91fbd3f3a501c5cd0fb9309418eebeae
    domain: light
  actions:
  - action: notify.mobile_app_roberts_iphone
    metadata: {}
    data:
      message: AI becul aprins in dormitor
      title: 'Reminder:'
  mode: single
- id: '1750874751938'
  alias: ceva
  description: ''
  triggers:
  - trigger: conversation
    command:
    - '{number}'
  conditions: []
  actions:
  - set_conversation_response: Ai spus {{ trigger.slots.number }}
  mode: single
- id: '1750881513295'
  alias: Porneste AC
  description: ''
  triggers:
  - trigger: conversation
    command: Pornește aerul condiționat
  conditions: []
  actions:
  - action: google_assistant_sdk.send_text_command
    metadata: {}
    data:
      command: '"Turn ON Split AC"'
  mode: single
- id: '1751211672229'
  alias: Temperatura dormitor
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Temperatura dormitor
  conditions: []
  actions:
  - action: google_assistant_sdk.send_text_command
    metadata: {}
    data:
      command: 'action: google_assistant_sdk.send_text_command data:   command: "How
        many degrees are there in the bedroom"'
      media_player: media_player.home_assistant_voice_092ccd_media_player
  mode: single
- id: '1751228641750'
  alias: HA Custom Responses
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.home_assistant_voice_092ccd_wake_word_detect
    to: 'on'
  conditions: []
  actions:
  - action: media_player.play_media
    target:
      entity_id: media_player.home_assistant_voice_092ccd_media_player
    data:
      media_content_id: media-source://tts/tts.home_assistant_cloud?message=Cum+te+pot+ajuta%0A&language=ro-RO&voice=AlinaNeural
      media_content_type: audio/mp3
    metadata:
      title: 'Cum te pot ajuta

        '
      thumbnail: https://brands.home-assistant.io/_/cloud/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: audio/mp3
        media_content_id: media-source://tts/tts.home_assistant_cloud?message=Cum+te+pot+ajuta%0A&language=ro-RO&voice=AlinaNeural
  mode: single
- id: '1751234817024'
  alias: Umiditate dormitor
  description: ''
  triggers:
  - trigger: conversation
    command: Umiditate dormitor
  conditions: []
  actions:
  - action: google_assistant_sdk.send_text_command
    metadata: {}
    data:
      command: 'action: google_assistant_sdk.send_text_command data:   command: "What
        is the humidity in the bedroom"'
  mode: single
- id: '1751408104227'
  alias: MotionActivatedLight
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.presence_sensor_fp2_fc03_presence_sensor_1
      light_target:
        device_id: 4ce43f89962024ede5b58424cd89a024
      no_motion_wait: 10
- id: '1751408242608'
  alias: Automatizare Bec Prezenta
  description: ''
  triggers:
  - type: occupied
    device_id: 1bb47a2dce9407d04147a5e6dee5698f
    entity_id: 48c9e4799bdd26678ce155512853376d
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: sun
    after: sunset
  actions:
  - type: turn_on
    device_id: 4ce43f89962024ede5b58424cd89a024
    entity_id: 91fbd3f3a501c5cd0fb9309418eebeae
    domain: light
    brightness_pct: 90
  mode: single
- id: '1752173588940'
  alias: Control motor_inainte 10s ON / 5s OFF pe temperatura si timp
  description: ''
  triggers:
  - seconds: /15
    trigger: time_pattern
  conditions:
  - condition: time
    after: '10:00:00'
    before: '16:00:00'
  - condition: template
    value_template: '{{ state_attr(''weather.forecast_home'', ''temperature'') | float
      > 25 }}'
  actions:
  - action: script.porneste_motor_10sec
    data: {}
  mode: single
